excerpt_separator: "<!--more-->"
gems: [jekyll-paginate, jekyll-less, jekyll/tagging]
tag_page_layout: archive
tag_page_dir: tag
markdown: redcarpet
highlighter: "pygments"
permalink: /:year/:month/:title
paginate: 10
url: http://greweb.me
name: "@Greweb"
description: "embrace standard web technologies for web, games and mobile apps"

tags:
  template: _layouts/archive
  title: "{tag}"
